### ISSUE TITLE
Youtube - https://youtube.com/devicesupport issue

### ISSUE THREAD

**Issue by michaelh99** [mistic100/Piwigo-Embedded-Videos#3]
All new embedded videos show the title "Youtube - https://youtube.com/devicesupport issue" and have no preview image.

Further discussion here
http://piwigo.org/forum/viewtopic.php?pid=159337#p159337

**Comment by mistic100** [comment]
GOD DAMN IT !!
there was a nice public API and now the only usable API requires authentication or use the very limited oEmbed API

> http://www.youtube.com/oembed?url=http://www.youtube.com/watch?v=uq4RON131Sk&format=json

I will certainly not implement the V3 API, oAuth give headaches and users should not but required to register an app in order to embed their own videos !

**Comment by michaelh99** [comment]
thanks
