### ISSUE TITLE
Register video several times in different folders

### ISSUE THREAD

**Issue by juliogomez** [mistic100/Piwigo-Embedded-Videos#6]
Let me start by saying I love this plugin!

I have one single video I would like to register in 3 different folders, but the plugin does now allow me to do it, as it says the video is already registered in the first one.

Would there be any quick workaround to do this? Or would it need new code?

Many thanks in advance!

**Comment by mistic100** [comment]
Videos are treated by Piwigo like standard elements. Go to the Batch Manager or the properties page of the video and associate the video to another album.

**Comment by juliogomez** [comment]
Fantastic, many thanks for your help!
